export const lightTheme = {
    bgColor: '#fffff',
    textColorDefault: 'black',
    textColorGrey: '#7a7a7a',
    textColorLight: '#ffffff',
    borderColor: '#D9E1E8',
    primaryColor: '#3d7eff',
    boxShadow: '#efefef',
    buttonDefault: '#efefef',
    barStopColorStart: '#dddaff',
    barStopColorEnd: '#f7ecff',
    barSelectedColor: '#bbb4ff',
    areaStroke: '#4d97cf',
    areaStopColorStart: '#a8d4f6',
    areaStopColorEnd: '#ffffff',
    referenceAreaFill: '#DCFF04',
    zoomInBoxBorder: '#006eff',
    zoomInBoxBg: '#85bff57b',
    zoomInLabel: '#0d2d6f',
    axisStroke: '#555555dd',
    brushFill: '#787E8320',
    tooltipBg: '#ffffffc0',
};

export const darkTheme = {
    bgColor: '#01081f',
    textColorDefault: '#E8EEF3',
    textColorGrey: '#B4BEC8',
    textColorLight: '#ffffff',
    borderColor: '#697179',
    primaryColor: '#3d7eff',
    boxShadow: '#414141',
    buttonDefault: '#4F5D69',
    barStopColorStart: '#4C1FCD',
    barStopColorEnd: '#815FE0',
    barSelectedColor: '#815FE0',
    areaStroke: '#04E1FF',
    areaStopColorStart: '#00cfde',
    areaStopColorEnd: '#ffffff',
    referenceAreaFill: '#AFFF04',
    zoomInBoxBorder: '#00FFC2',
    zoomInBoxBg: '#00FFC250',
    zoomInLabel: '#DCE4EB',
    axisStroke: '#69747C',
    brushFill: '#787E8320',
    tooltipBg: 'rgba(10, 31, 50, 0.6)',
};

export const theme = {
    lightTheme,
    darkTheme,
};
